### ISSUE TITLE
DebugApplication causes recursion loop

### ISSUE THREAD

**Issue by fusionbeam** [mitsuhiko/werkzeug#726]
Hi,

Since upgrading Werkzeug (0.10.4) I get a "Maximum recursion depth exceeded" when Flask brings up the debug application.

I have Flask = 0.10.1, Werkzeug (0.10.4) and I am using uwsgi. Here is the relevant code:

app creation
```
app = Flask(package_name, instance_relative_config=True)

    rv = os.environ.get('RUN_ENV')
    app.config.from_object('settings.%s' % rv)
    app.config.from_object(settings_override)

    if app.config.get('DEBUG'):
        from werkzeug.debug import DebuggedApplication
        app.wsgi_app = DebuggedApplication(app, evalex=True)
```

uwsgi.py
```
app = DispatcherMiddleware(frontend.create_app(), {
    '/admin': admin.create_app(),
    '/api': api.create_app()
})
```

Anyone might have a clue on why is this happening ?

Here is the traceback:

```
Traceback (most recent call last):
  File "/Users/ra/code/truepath/nms/env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/ra/code/truepath/nms/env/lib/python2.7/site-packages/werkzeug/debug/__init__.py", line 166, in __call__
    if request.args.get('__debugger__') == 'yes':
  File "/Users/ra/code/truepath/nms/env/lib/python2.7/site-packages/werkzeug/utils.py", line 71, in __get__
    value = self.func(obj)
  File "/Users/ra/code/truepath/nms/env/lib/python2.7/site-packages/werkzeug/wrappers.py", line 429, in args
    cls=self.parameter_storage_class)
  File "/Users/ra/code/truepath/nms/env/lib/python2.7/site-packages/werkzeug/urls.py", line 723, in url_decode
    include_empty, errors))
  File "/Users/ra/code/truepath/nms/env/lib/python2.7/site-packages/werkzeug/datastructures.py", line 373, in __init__
    for key, value in mapping or ():
  File "/Users/ra/code/truepath/nms/env/lib/python2.7/site-packages/werkzeug/urls.py", line 779, in _url_decode_impl
    key = url_unquote_plus(key, charset, errors)
  File "/Users/ra/code/truepath/nms/env/lib/python2.7/site-packages/werkzeug/urls.py", line 545, in url_unquote_plus
    return url_unquote(s, charset, errors)
  File "/Users/ra/code/truepath/nms/env/lib/python2.7/site-packages/werkzeug/urls.py", line 522, in url_unquote
    rv = _unquote_to_bytes(string, unsafe)
  File "/Users/ra/code/truepath/nms/env/lib/python2.7/site-packages/werkzeug/urls.py", line 351, in _unquote_to_bytes
    if isinstance(string, text_type):
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

**Comment by warik** [comment]
You should pass app.wsgi_app to DebuggedApplication instead of just app

**Comment by untitaker** [comment]
What @warik said.

**Comment by fusionbeam** [comment]
thanks for the quick answer.
I've changed it
``` app.wsgi_app = DebuggedApplication(app.wsgi_app, evalex=True)
```
Now the debugger does not show at all. 
here is my entire uwsgi.py

```
app = DispatcherMiddleware(frontend.create_app(), {
    '/admin': admin.create_app(),
    '/api': api.create_app()
})

app = frontend.create_app()

if __name__ == "__main__":
    app.debug = True
    run_simple('0.0.0.0', 5000, app, use_reloader=False, use_debugger=True)
```

**Comment by untitaker** [comment]
Please use proper formatting, this post is barely readable. You're defining the app-variable twice. What is `create_app`? Why not use the app object directly?

**Comment by warik** [comment]
As far as i remember there is no need to use DebuggedApplication middleware explicitly. It will be added by means of flag use_debugger if You are using flask application.

**Comment by fusionbeam** [comment]
For whom it may concern, it turned out that I had the following settings:
PROPAGATE_EXCEPTIONS = False
PRESERVE_CONTEXT_ON_EXCEPTION = False
and this was presenting the debugger from being called.
