### ISSUE TITLE
UnicodeError is raised when the url contains invalid unicode

### ISSUE THREAD

**Issue by Javantea** [mitsuhiko/werkzeug#808]
Similar to #640, a crafted URL can cause a 500 error in Werkzeug _internal._encode_idna
The line of code is here: [werkzeug/_internal.py:305](https://github.com/mitsuhiko/werkzeug/blob/master/werkzeug/_internal.py#L305)

```
127.0.0.1 - - [11/Nov/2015 14:34:33] "GET http://google.com HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/home/dulwich/xjdic2/venv/lib/python3.3/site-packages/werkzeug/serving.py", line 180, in run_wsgi
    execute(self.server.app)
  File "/home/dulwich/xjdic2/venv/lib/python3.3/site-packages/werkzeug/serving.py", line 168, in execute
    application_iter = app(environ, start_response)
  File "/home/dulwich/xjdic2/venv/lib/python3.3/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/dulwich/xjdic2/venv/lib/python3.3/site-packages/flask/app.py", line 1812, in wsgi_app
    ctx = self.request_context(environ)
  File "/home/dulwich/xjdic2/venv/lib/python3.3/site-packages/flask/app.py", line 1773, in request_context
    return RequestContext(self, environ)
  File "/home/dulwich/xjdic2/venv/lib/python3.3/site-packages/flask/ctx.py", line 224, in __init__
    self.url_adapter = app.create_url_adapter(self.request)
  File "/home/dulwich/xjdic2/venv/lib/python3.3/site-packages/flask/app.py", line 1602, in create_url_adapter
    server_name=self.config['SERVER_NAME'])
  File "/home/dulwich/xjdic2/venv/lib/python3.3/site-packages/werkzeug/routing.py", line 1248, in bind_to_environ
    query_args=query_args)
  File "/home/dulwich/xjdic2/venv/lib/python3.3/site-packages/werkzeug/routing.py", line 1167, in bind
    server_name = _encode_idna(server_name)
  File "/home/dulwich/xjdic2/venv/lib/python3.3/site-packages/werkzeug/_internal.py", line 304, in _encode_idna
    parts[idx] = part.encode('idna')
  File "/usr/lib64/python3.3/encodings/idna.py", line 181, in encode
    result.extend(ToASCII(label))
  File "/usr/lib64/python3.3/encodings/idna.py", line 76, in ToASCII
    label = nameprep(label)
  File "/usr/lib64/python3.3/encodings/idna.py", line 38, in nameprep
    raise UnicodeError("Invalid character %r" % c)
UnicodeError: Invalid character '\x81'
```

To reproduce the error:
```sh
echo -n $'GET http://www.google.com\x81 HTTP/1.1\r\nHost:localhost\r\n\r\n' | nc localhost 5000
```
or in Python:
```python
HOST, PORT = 'localhost', 5001

family = socket.AF_UNSPEC
socktype = socket.SOCK_STREAM

gai = socket.getaddrinfo(HOST, PORT, family, socktype)

for ai in gai:
	print(ai)
	family, socktype, proto, canonname, sockaddr = ai
	try:
		s = socket.socket(family, socktype, proto)
		s.connect(sockaddr[:2])
		break
	except ConnectionRefusedError:
		pass
	except OSError:
		pass
	#end try
#next ai

# The \x81 is the problem, but it's specifically this type of url that gets to 
# _internal._encode_idna
s.send(b'GET http://google.com\x81 HTTP/1.1\r\nHost: http://google.com\r\n\r\n')
data = b'#'
while data != b'':
	data = s.recv(1024)
	print(data)
#loop
```
This request is handled differently by werkzeug than by any other server. This could make it so that an attacker can accurately determine that werkzeug is being used to speed up recon. It may be worthwhile to consider returning 400 (nginx) or 200 (apache) or 404 (Python http.server) so that an administrator can hide their response types among different servers. See this response:
```
echo -n $'GET http://www.google.com© HTTP/1.1\r\nHost:localhost\r\n\r\n' | nc localhost 5001
HTTP/1.0 301 MOVED PERMANENTLY
Content-Type: text/html; charset=utf-8
Content-Length: 271
Location: http://www.google.xn--com-1ea8z/
...
```

**Comment by mitsuhiko** [comment]
This will be fixed in 0.11.2.
