### ISSUE TITLE
Werkzeug crashes on URL when using spaces in cURL

### ISSUE THREAD

**Issue by xavierhardy** [mitsuhiko/werkzeug#827]
This commands crashes the Werkzeug 0.11.2 and sends back an empty reply (no 500 nor 400).
```
curl "http://localhost:5000/v1.0/something/test=' '"
```
This does not crash with Werkzeug 0.10.4 and sends a bad request.

```
Traceback (most recent call last):
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 53054)
  File "/usr/local/opt/python-3.4.2/lib/python3.4/socketserver.py", line 305, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/opt/python-3.4.2/lib/python3.4/socketserver.py", line 331, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/opt/python-3.4.2/lib/python3.4/socketserver.py", line 344, in finish_request
    self.RequestHandlerClass(request, client_address, self)
----------------------------------------
  File "/usr/local/opt/python-3.4.2/lib/python3.4/socketserver.py", line 669, in __init__
    self.handle()
  File "/usr/src/something/env/lib/python3.4/site-packages/werkzeug/serving.py", line 217, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/local/opt/python-3.4.2/lib/python3.4/http/server.py", line 398, in handle
    self.handle_one_request()
  File "/usr/src/something/env/lib/python3.4/site-packages/werkzeug/serving.py", line 251, in handle_one_request
    elif self.parse_request():
  File "/usr/local/opt/python-3.4.2/lib/python3.4/http/server.py", line 314, in parse_request
    self.send_error(400, "Bad request syntax (%r)" % requestline)
  File "/usr/local/opt/python-3.4.2/lib/python3.4/http/server.py", line 428, in send_error
    self.log_error("code %d, message %s", code, message)
  File "/usr/src/something/env/lib/python3.4/site-packages/werkzeug/serving.py", line 273, in log_error
    self.log('error', *args)
  File "/usr/src/something/env/lib/python3.4/site-packages/werkzeug/serving.py", line 279, in log
    _log(type, '%s - - [%s] %s\n' % (self.address_string(),
  File "/usr/src/something/env/lib/python3.4/site-packages/werkzeug/serving.py", line 267, in address_string
    return self.environ['REMOTE_ADDR']
AttributeError: 'WSGIRequestHandler' object has no attribute 'environ'
```

In version 0.10.4, we get a proper HTML 400 bad request page.
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
        "http://www.w3.org/TR/html4/strict.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
        <title>Error response</title>
    </head>
    <body>
        <h1>Error response</h1>
        <p>Error code: 400</p>
        <p>Message: Bad request syntax ("GET /v1.0/something/test=' ' HTTP/1.1").</p>
        <p>Error code explanation: 400 - Bad request syntax or unsupported method.</p>
    </body>
</html>
```

**Comment by brentonr** [comment]
This should be fixed with #838 when it gets merged

**Comment by GrappigPanda** [comment]
This can probably be marked as closed. 11.5 is on pypi with this fix as of yesterday.

**Comment by untitaker** [comment]
Oh yeah.
