### ISSUE TITLE
Seeing an issue on ubuntu

### ISSUE THREAD

**Issue by sandeep-foghorn** [mitsuhiko/werkzeug#858]
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "werkzeug/serving.py", line 217, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "werkzeug/serving.py", line 252, in handle_one_request
    return self.run_wsgi()
  File "werkzeug/serving.py", line 200, in run_wsgi
    from debug.tbtools import get_current_traceback
ImportError: No module named debug.tbtools

But if I try from python command line, I can import the module

**Comment by mitsuhiko** [comment]
I assume you have a very old version of werkzeug? The line in werkzeug.serving does not look like that.
